using CourseProject.DAL.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CourseProject.DAL.EntityExtensions; 

public static class EquipmentItemValueEntityExtensions {

    public static void Configure(this EntityTypeBuilder<EquipmentItemValue> builder) {

        builder.HasData(new EquipmentItemValue[] {
            new() { EquipmentItemId = 1, Value = "Engine 1", Price = 10000 },
            new() { EquipmentItemId = 1, Value = "Engine 2", Price = 15000 },
            new() { EquipmentItemId = 1, Value = "Engine 3", Price = 8000 },
            new() { EquipmentItemId = 2, Value = "Color 1", Price = 1000 },
            new() { EquipmentItemId = 2, Value = "Color 2", Price = 1500 },
            new() { EquipmentItemId = 2, Value = "Color 3", Price = 800 },
            new() { EquipmentItemId = 3, Value = "Transmission 1", Price = 15000 },
            new() { EquipmentItemId = 3, Value = "Transmission 2", Price = 12000 },
            new() { EquipmentItemId = 3, Value = "Transmission 3", Price = 9000 },
            new() { EquipmentItemId = 4, Value = "Engine 1", Price = 10000 },
            new() { EquipmentItemId = 4, Value = "Engine 2", Price = 15000 },
            new() { EquipmentItemId = 4, Value = "Engine 3", Price = 8000 },
            new() { EquipmentItemId = 5, Value = "Color 1", Price = 1000 },
            new() { EquipmentItemId = 5, Value = "Color 2", Price = 1500 },
            new() { EquipmentItemId = 5, Value = "Color 3", Price = 800 },
            new() { EquipmentItemId = 6, Value = "Transmission 1", Price = 15000 },
            new() { EquipmentItemId = 6, Value = "Transmission 2", Price = 12000 },
            new() { EquipmentItemId = 6, Value = "Transmission 3", Price = 9000 },
            new() { EquipmentItemId = 7, Value = "Engine 1", Price = 10000 },
            new() { EquipmentItemId = 7, Value = "Engine 2", Price = 15000 },
            new() { EquipmentItemId = 7, Value = "Engine 3", Price = 8000 },
            new() { EquipmentItemId = 8, Value = "Color 1", Price = 1000 },
            new() { EquipmentItemId = 8, Value = "Color 2", Price = 1500 },
            new() { EquipmentItemId = 8, Value = "Color 3", Price = 800 },
            new() { EquipmentItemId = 9, Value = "Transmission 1", Price = 15000 },
            new() { EquipmentItemId = 9, Value = "Transmission 2", Price = 12000 },
            new() { EquipmentItemId = 9, Value = "Transmission 3", Price = 9000 },
            new() { EquipmentItemId = 10, Value = "Engine 1", Price = 10000 },
            new() { EquipmentItemId = 10, Value = "Engine 2", Price = 15000 },
            new() { EquipmentItemId = 10, Value = "Engine 3", Price = 8000 },
            new() { EquipmentItemId = 11, Value = "Color 1", Price = 1000 },
            new() { EquipmentItemId = 11, Value = "Color 2", Price = 1500 },
            new() { EquipmentItemId = 11, Value = "Color 3", Price = 800 },
            new() { EquipmentItemId = 12, Value = "Transmission 1", Price = 15000 },
            new() { EquipmentItemId = 12, Value = "Transmission 2", Price = 12000 },
            new() { EquipmentItemId = 12, Value = "Transmission 3", Price = 9000 },
            new() { EquipmentItemId = 13, Value = "Engine 1", Price = 10000 },
            new() { EquipmentItemId = 13, Value = "Engine 2", Price = 15000 },
            new() { EquipmentItemId = 13, Value = "Engine 3", Price = 8000 },
            new() { EquipmentItemId = 14, Value = "Color 1", Price = 1000 },
            new() { EquipmentItemId = 14, Value = "Color 2", Price = 1500 },
            new() { EquipmentItemId = 14, Value = "Color 3", Price = 800 },
            new() { EquipmentItemId = 15, Value = "Transmission 1", Price = 15000 },
            new() { EquipmentItemId = 15, Value = "Transmission 2", Price = 12000 },
            new() { EquipmentItemId = 15, Value = "Transmission 3", Price = 9000 },
            new() { EquipmentItemId = 16, Value = "Engine 1", Price = 10000 },
            new() { EquipmentItemId = 16, Value = "Engine 2", Price = 15000 },
            new() { EquipmentItemId = 16, Value = "Engine 3", Price = 8000 },
            new() { EquipmentItemId = 17, Value = "Color 1", Price = 1000 },
            new() { EquipmentItemId = 17, Value = "Color 2", Price = 1500 },
            new() { EquipmentItemId = 17, Value = "Color 3", Price = 800 },
            new() { EquipmentItemId = 18, Value = "Transmission 1", Price = 15000 },
            new() { EquipmentItemId = 18, Value = "Transmission 2", Price = 12000 },
            new() { EquipmentItemId = 18, Value = "Transmission 3", Price = 9000 },
            new() { EquipmentItemId = 19, Value = "Engine 1", Price = 10000 },
            new() { EquipmentItemId = 19, Value = "Engine 2", Price = 15000 },
            new() { EquipmentItemId = 19, Value = "Engine 3", Price = 8000 },
            new() { EquipmentItemId = 20, Value = "Color 1", Price = 1000 },
            new() { EquipmentItemId = 20, Value = "Color 2", Price = 1500 },
            new() { EquipmentItemId = 20, Value = "Color 3", Price = 800 },
            new() { EquipmentItemId = 21, Value = "Transmission 1", Price = 15000 },
            new() { EquipmentItemId = 21, Value = "Transmission 2", Price = 12000 },
            new() { EquipmentItemId = 21, Value = "Transmission 3", Price = 9000 },
            new() { EquipmentItemId = 22, Value = "Engine 1", Price = 10000 },
            new() { EquipmentItemId = 22, Value = "Engine 2", Price = 15000 },
            new() { EquipmentItemId = 22, Value = "Engine 3", Price = 8000 },
            new() { EquipmentItemId = 23, Value = "Color 1", Price = 1000 },
            new() { EquipmentItemId = 23, Value = "Color 2", Price = 1500 },
            new() { EquipmentItemId = 23, Value = "Color 3", Price = 800 },
            new() { EquipmentItemId = 24, Value = "Transmission 1", Price = 15000 },
            new() { EquipmentItemId = 24, Value = "Transmission 2", Price = 12000 },
            new() { EquipmentItemId = 24, Value = "Transmission 3", Price = 9000 },
            new() { EquipmentItemId = 25, Value = "Engine 1", Price = 10000 },
            new() { EquipmentItemId = 25, Value = "Engine 2", Price = 15000 },
            new() { EquipmentItemId = 25, Value = "Engine 3", Price = 8000 },
            new() { EquipmentItemId = 26, Value = "Color 1", Price = 1000 },
            new() { EquipmentItemId = 26, Value = "Color 2", Price = 1500 },
            new() { EquipmentItemId = 26, Value = "Color 3", Price = 800 },
            new() { EquipmentItemId = 27, Value = "Transmission 1", Price = 15000 },
            new() { EquipmentItemId = 27, Value = "Transmission 2", Price = 12000 },
            new() { EquipmentItemId = 27, Value = "Transmission 3", Price = 9000 },
            new() { EquipmentItemId = 28, Value = "Engine 1", Price = 10000 },
            new() { EquipmentItemId = 28, Value = "Engine 2", Price = 15000 },
            new() { EquipmentItemId = 28, Value = "Engine 3", Price = 8000 },
            new() { EquipmentItemId = 29, Value = "Color 1", Price = 1000 },
            new() { EquipmentItemId = 29, Value = "Color 2", Price = 1500 },
            new() { EquipmentItemId = 29, Value = "Color 3", Price = 800 },
            new() { EquipmentItemId = 30, Value = "Transmission 1", Price = 15000 },
            new() { EquipmentItemId = 30, Value = "Transmission 2", Price = 12000 },
            new() { EquipmentItemId = 30, Value = "Transmission 3", Price = 9000 },
        });
    }

}